version: '3.3'

volumes:
  pg_data_foodgram:
  static_foodgram:
  media_foodgram:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data

  backend:
    image: danilch1rkov/backend
    env_file: .env
    volumes:
      - static_foodgram:/backend_static
      - media_foodgram:/app/media/
    depends_on:
      - db

  frontend:
    image: danilch1rkov/frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_foodgram:/static

  nginx:
    image: danilch1rkov/nginx
    ports:
      - 7000:80
    volumes:
      - static_foodgram:/static
      - media_foodgram:/app/media/
    depends_on:
      - backend