# Generated by Django 3.2 on 2024-07-27 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_recipie_ingredientrecipie_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipie',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Количество ингредиентов не может быть меньше 1')], verbose_name='Количество'),
        ),
    ]
